In [192]:
import pandas as pd
from sklearn.svm import SVC
from sklearn.model_selection import train_test_split

In [193]:
games_2021 = pd.read_json("../data/games_2021.json")
games_2021.columns

Index(['id', 'season', 'week', 'season_type', 'start_date', 'start_time_tbd',
       'neutral_site', 'conference_game', 'attendance', 'venue_id', 'venue',
       'home_id', 'home_team', 'home_conference', 'home_division',
       'home_points', 'home_line_scores', 'home_post_win_prob',
       'home_pregame_elo', 'home_postgame_elo', 'away_id', 'away_team',
       'away_conference', 'away_division', 'away_points', 'away_line_scores',
       'away_post_win_prob', 'away_pregame_elo', 'away_postgame_elo',
       'excitement_index', 'highlights', 'notes'],
      dtype='object')

In [194]:
games_2021.to_csv("games_2021.json")
games_2021

,id,season,week,season_type,start_date,start_time_tbd,neutral_site,conference_game,attendance,venue_id,...,away_conference,away_division,away_points,away_line_scores,away_post_win_prob,away_pregame_elo,away_postgame_elo,excitement_index,highlights,notes
0,401282714,2021,1,regular,2021-08-28T17:20:00.000Z,False,False,True,41064.0,3832.0,...,Big Ten,fbs,22,"[0, 9, 7, 6]",0.594339,1503.0,1484.0,5.485981,NaN,None
1,401286187,2021,1,regular,2021-08-28T18:00:00.000Z,False,False,False,26043.0,3660.0,...,FBS Independents,fbs,0,"[0, 0, 0, 0]",0.001032,1223.0,1122.0,1.535556,NaN,None
2,401329133,2021,1,regular,2021-08-28T19:00:00.000Z,False,True,True,NaN,3861.0,...,SIAC,ii,20,"[6, 7, 0, 7]",NaN,NaN,NaN,NaN,NaN,None
3,401309833,2021,1,regular,2021-08-28T19:30:00.000Z,False,False,False,32982.0,1056.0,...,Mountain West,fbs,10,"[3, 0, 7, 0]",0.001076,1466.0,1378.0,1.391185,NaN,None
4,401328337,2021,1,regular,2021-08-28T22:00:00.000Z,False,False,False,NaN,3829.0,...,OVC,fcs,21,"[0, 7, 7, 7]",NaN,NaN,NaN,NaN,NaN,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2403,401391131,2021,15,regular,2021-12-11T17:00:00.000Z,False,False,False,NaN,3714.0,...,Southern,fcs,3,"[0, 0, 3, 0]",NaN,NaN,NaN,NaN,NaN,FCS Championship - Quarterfinals
2404,401391133,2021,15,regular,2021-12-11T19:00:00.000Z,False,False,False,NaN,717.0,...,MVFC,fcs,35,"[7, 7, 14, 7]",NaN,NaN,NaN,NaN,NaN,FCS Championship - Quarterfinals
2405,401301056,2021,15,regular,2021-12-11T20:00:00.000Z,False,False,False,82282.0,3839.0,...,American Athletic,fbs,17,"[7, 0, 7, 3]",0.995164,1330.0,1355.0,6.799666,NaN,None
2406,401391051,2021,15,regular,2021-12-11T20:30:00.000Z,False,False,False,NaN,3960.0,...,Pennsylvania State Athletic,ii,7,"[7, 0, 0, 0]",NaN,NaN,NaN,NaN,NaN,Division II Championship - Semifinal
2407,401391132,2021,15,regular,2021-12-12T01:30:00.000Z,False,False,False,NaN,3647.0,...,Big Sky,fcs,42,"[14, 14, 7, 7]",NaN,NaN,NaN,NaN,NaN,FCS Championship - Quarterfinals

In [195]:
big_ten = pd.read_json("../data/big_ten_2021.json")

big_ten

            id                                              teams
0    401331447  [{'school': 'Michigan', 'conference': 'Big Ten...
1    401282179  [{'school': 'UT San Antonio', 'conference': 'C...
2    401282772  [{'school': 'Western Michigan', 'conference': ...
3    401282809  [{'school': 'Ohio State', 'conference': 'Big T...
4    401282804  [{'school': 'Indiana State', 'conference': 'MV...
..         ...                                                ...
101  401282820  [{'school': 'Connecticut', 'conference': 'FBS ...
102  401282629  [{'school': 'Miami', 'conference': 'ACC', 'hom...
103  401282628  [{'school': 'Duke', 'conference': 'ACC', 'home...
104  401282765  [{'school': 'Maryland', 'conference': 'Big Ten...
105  401282715  [{'school': 'Illinois', 'conference': 'Big Ten...

[106 rows x 2 columns]

In [196]:
df = pd.merge(games_2021, big_ten);
df

,id,season,week,season_type,start_date,start_time_tbd,neutral_site,conference_game,attendance,venue_id,...,away_division,away_points,away_line_scores,away_post_win_prob,away_pregame_elo,away_postgame_elo,excitement_index,highlights,notes,teams
0,401282714,2021,1,regular,2021-08-28T17:20:00.000Z,False,False,True,41064.0,3832.0,...,fbs,22,"[0, 9, 7, 6]",0.594339,1503.0,1484.0,5.485981,NaN,None,"[{'school': 'Illinois', 'conference': 'Big Ten..."
1,401282789,2021,1,regular,2021-09-03T00:00:00.000Z,False,False,True,50805.0,3953.0,...,fbs,45,"[7, 3, 21, 14]",0.829314,1905.0,1908.0,4.281207,NaN,None,"[{'school': 'Minnesota', 'conference': 'Big Te..."
2,401282782,2021,1,regular,2021-09-04T01:00:00.000Z,False,False,True,34248.0,3911.0,...,fbs,38,"[14, 7, 7, 10]",0.991311,1424.0,1489.0,3.308017,NaN,None,"[{'school': 'Northwestern', 'conference': 'Big..."
3,401282772,2021,1,regular,2021-09-04T16:00:00.000Z,False,False,False,109295.0,3558.0,...,fbs,14,"[7, 0, 0, 7]",0.001313,1510.0,1429.0,2.323598,NaN,None,"[{'school': 'Western Michigan', 'conference': ..."
4,401282815,2021,1,regular,2021-09-04T16:00:00.000Z,False,False,True,76832.0,347.0,...,fbs,16,"[0, 0, 7, 9]",0.181436,1668.0,1685.0,8.626229,NaN,None,"[{'school': 'Wisconsin', 'conference': 'Big Te..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
101,401282753,2021,13,regular,2021-11-27T20:30:00.000Z,False,False,True,61320.0,3907.0,...,fbs,7,"[7, 0, 0, 0]",0.002275,1308.0,1245.0,3.363164,NaN,None,"[{'school': 'Indiana', 'conference': 'Big Ten'..."
102,401282722,2021,13,regular,2021-11-27T20:30:00.000Z,False,False,True,27624.0,3832.0,...,fbs,14,"[0, 7, 0, 7]",0.001822,1380.0,1292.0,2.255525,NaN,None,"[{'school': 'Northwestern', 'conference': 'Big..."
103,401282785,2021,13,regular,2021-11-27T20:30:00.000Z,False,False,True,66312.0,3936.0,...,fbs,27,"[7, 7, 6, 7]",0.220247,1813.0,1808.0,8.074886,NaN,None,"[{'school': 'Penn State', 'conference': 'Big T..."
104,401282794,2021,13,regular,2021-11-27T21:00:00.000Z,False,False,True,49736.0,3953.0,...,fbs,13,"[0, 10, 3, 0]",0.030435,1906.0,1870.0,6.079034,NaN,None,"[{'school': 'Wisconsin', 'conference': 'Big Te..."
105,401331447,2021,14,regular,2021-12-05T01:00:00.000Z,False,True,True,67183.0,3812.0,...,fbs,42,"[14, 0, 7, 21]",0.935983,1988.0,2065.0,1.873741,NaN,None,"[{'school': 'Michigan', 'conference': 'Big Ten..."

In [197]:
for team in df["teams"]:
    for i in team:
        stats = i["stats"]
        for j in stats:
            feature = j["category"]
            stat_val = j["stat"]
        df[feature] = stat_val

In [198]:
for team in df["teams"]:
    for i in team:
        school = i['school']
    df["teams"] = school